name: Semantic Release
description: Publish to GitHub releases and/or NPM via Semantic Release.
author: glzr.io

branding:
  icon: activity
  color: gray-dark

inputs:
  release-branch:
    description: Branch on which new releases are created from.
    default: main

  gh-publish:
    description: Whether to publish a GitHub release.
    default: false

  gh-draft-release:
    description: Whether to publish the GitHub release as a draft.
    default: true

  gh-release-header:
    description: Header text to show at the top of the release.
    default: ''

  gh-token:
    description: GitHub token for authentication.

  gh-assets:
    description: |
      JSON string of assets to attach to the GitHub release.
      eg. [{ "path": "dist/asset.min.css", "label": "CSS" }]

  npm-publish:
    description: Whether to publish to NPM.
    default: false

  npm-token:
    description: NPM token for authentication.

  npm-package-manager:
    description: |
      Package manager used to publish the package (either 'npm' or
      'pnpm'). Setting this to 'pnpm' allows workspace:* dependencies to
      be used.
    default: npm

  npm-package-root:
    description: |
      Path to directory to publish (must contain a `package.json` file).

runs:
  using: node20
  main: dist/index.js
