name: Semantic Release
description: Publish to GitHub releases and/or NPM via Semantic Release.
author: glzr.io

branding:
  icon: activity
  color: gray-dark

inputs:
  is-prerelease:
    description: Whether to publish as a prelease.
    default: false

  prerelease-tag:
    description: Suffix to add for preleases in GH releases and NPM dist tags.
    default: next

  repository-url:
    description: URL to the Git repository (eg. 'git+https://github.com/glzr-io/actions.git').
    required: true

  release-branch:
    description: Branch on which new releases are created from.
    default: 'main'

  gh-publish:
    description: Whether to publish a GitHub release.
    default: false

  gh-token:
    description: GitHub token for authentication.

  gh-assets:
    description: |
      JSON string of assets to attach to the GitHub release.
      eg. [{ "path": "dist/asset.min.css", "label": "CSS" }]

  npm-publish:
    description: Whether to publish to NPM.
    default: false

  npm-token:
    description: NPM token for authentication.

runs:
  using: node20
  main: dist/index.js
