name: Semantic PRs
description: Check that PR title is valid.
author: glzr.io

branding:
  icon: activity
  color: gray-dark

inputs:
  gh_token:
    description: GitHub token for authentication.
    required: true

  allowed_scopes:
    description: |
      JSON string array of allowed scopes.
      eg. ['docs', 'lander']
    default: []

  example_title:
    description: Example of a good PR title.
    default: 'feat: add option to disable window transition animations'

  example_title_with_scope:
    description: Example of a good PR title with a scope.
    default: 'fix(utils): handle error when trimming string'

runs:
  using: node20
  main: dist/index.js
