name: 'Semantic PRs'
description: 'Check that PR title is valid.'
author: 'glzr.io'

branding:
  icon: 'activity'
  color: 'gray-dark'

inputs:
  gh_token:
    description: 'The GitHub token for authentication.'

runs:
  using: 'node20'
  main: 'dist/index.js'
