name: Semantic PRs
description: Check that PR title is valid.
author: glzr.io

branding:
  icon: activity
  color: gray-dark

inputs:
  gh-token:
    description: GitHub token for authentication.
    required: true

  allowed-scopes:
    description: |
      JSON string array of allowed scopes.
      eg. ['docs', 'lander']
    default: '[]'

  example-title:
    description: Example of a good PR title.
    default: 'feat: add option to disable window transition animations'

  example-title-with-scope:
    description: Example of a good PR title with a scope.
    default: 'fix(utils): handle error when trimming string'

runs:
  using: node20
  main: dist/index.js
