# This workflow ensures the `dist/` directory contains the expected
# transpiled code.
name: Dist check

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  dist-check:
    runs-on: ubuntu-latest
    steps:
      - uses: glzr-io/actions/setup-pnpm@main
        with:
          checkout: true
          node-version: 20

      - name: Build dist/ directories
        run: pnpm build

      # This will fail the workflow if the committed `dist/` directory is
      # different than the build output.
      - name: Compare directories
        run: |
          # Find all subdirectories that contain a dist/ folder.
          PACKAGES=$(find . -maxdepth 2 -type d -name "dist")

          for pkg in $PACKAGES; do
            echo "Checking dist/ directory in $pkg..."

            if [ "$(git diff --ignore-space-at-eol --text $pkg | wc -l)" -gt "0" ]; then
              echo "Detected uncommitted changes in $pkg. See status below:"
              git diff --ignore-space-at-eol --text $pkg
              exit 1
            fi
          done
